name: Build Java, Maven, Trivy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-save-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Build Environment
        run: |
          docker pull ubuntu:latest
          docker run -dit --name build-env ubuntu:latest bash

      - name: Install Java JDK 17, Maven, and Dependencies
        run: |
          docker exec build-env bash -c "
          apt update && apt upgrade -y &&
          apt install -y openjdk-17-jdk maven git nano net-tools curl wget gnupg subversion &&
          apt install -y jq &&
          java -version &&
          mvn -version &&
          git config --global http.sslVerify false"

      - name: Install Trivy and Dependencies
        run: |
          docker exec build-env bash -c "
          mkdir -p /tmp/trivy1 &&
          wget -O /tmp/trivy1/trivy_0.58.2_Linux-64bit.tar.gz https://github.com/aquasecurity/trivy/releases/download/v0.58.2/trivy_0.58.2_Linux-64bit.tar.gz &&
          tar -xzvf /tmp/trivy1/trivy_0.58.2_Linux-64bit.tar.gz -C /tmp/trivy1 &&
          cd /tmp/trivy1 &&
          ls -lRt /tmp/trivy1 &&
          ./trivy --version"

      - name: Install jq
        run: |
          docker exec build-env bash -c "
          wget -O jq https://github.com/stedolan/jq/releases/latest/download/jq-linux64 &&
          chmod +x jq &&
          mv jq /tmp/jq &&
          cd /tmp &&
          ./jq --version"

      - name: Commit Docker Changes
        run: |
          docker commit build-env custom-java-maven-trivy:latest

      - name: Save Docker Image as TAR
        run: |
          docker save -o java-maven-trivy.tar custom-java-maven-trivy:latest

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-maven-trivy-image
          path: java-maven-trivy.tar

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Registry
        run: |
          docker tag custom-java-maven-trivy:latest ${{ secrets.DOCKER_HUB_USERNAME }}/trivy-image:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/trivy-image:latest
          BUILD_TAG=${{ github.run_number }}
          docker tag custom-java-maven-trivy:latest ${{ secrets.DOCKER_HUB_USERNAME }}/trivy-image:${BUILD_TAG}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/trivy-image:${BUILD_TAG}
      - name: Cleanup Docker Container
        run: |
          docker rm -f build-env
