name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - az
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for better multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/rhel8-openjdk17-maven-node-az:${{ github.run_number }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rhel8-openjdk11-maven-node:${{ github.run_number }}
          docker tag  ${{ secrets.DOCKER_HUB_USERNAME }}/rhel8-openjdk11-maven-node:${{ github.run_number }} ${{ secrets.DOCKER_HUB_USERNAME }}/rhel8-openjdk11-maven-node:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rhel8-openjdk11-maven-node:latest
